export type RosterEntry = {
  name: string;
  last: string;
  role: string;
  group: string;
};

export const availableOfficerFiles: string[] = [
  "Acebo.jpg",
  "Aguilar.jpg",
  "Ahorro.jpg",
  "Andrada.jpg",
  "Arnoco.jpg",
  "Baloloy.jpg",
  "Belasa.jpg",
  "Bolibol.jpg",
  "Briones.png",
  "Buenaventura.jpg",
  "Capalaran.jpg",
  "Cruz.jpg",
  "Dela Rosa.jpg",
  "Delfin.jpg",
  "Dulay.jpg",
  "Espiritu.jpg",
  "Esplana.jpg",
  "Fabros.jpg",
  "Gaerlan.jpg",
  "Go.jpg",
  "Grace.jpg",
  "Landoy.jpg",
  "Leis.jpg",
  "Mayores.jpg",
  "Mendiola.jpg",
  "Morcozo.jpg",
  "MrMalihum.jpg",
  "MsGongora.jpg",
  "Padernal.jpg",
  "Parina.jpg",
  "Pascual.jpg",
  "Pasion.jpg",
  "Plarisan.jpg",
  "Radima.jpg",
  "Rayos.jpg",
  "Rectin.jpg",
  "Rendon.jpg",
  "Salandanan.jpg",
  "Santos.jpg",
  "Saraga.jpg",
  "Soldao.jpg",
  "Suela.jpg",
  "Tomale.jpg",
  "Valle.jpg",
  "Vallejo.jpg",
  "Villagracia.jpg",
];

export const roster: RosterEntry[] = [
  {
    name: "John Benedict Leis",
    last: "Leis",
    role: "President",
    group: "Executive",
  },
  {
    name: "Micko Pascual",
    last: "Pascual",
    role: "Vice President of Internals",
    group: "Executive",
  },
  {
    name: "Joseph Angelo Cruz",
    last: "Cruz",
    role: "Vice President of Externals",
    group: "Executive",
  },

  {
    name: "Clarence Jeane Bolibol",
    last: "Bolibol",
    role: "Secretary of Records",
    group: "Secretaries",
  },
  {
    name: "Jannah Mari Baloloy",
    last: "Baloloy",
    role: "Secretary of Finance",
    group: "Secretaries",
  },
  {
    name: "Cayril Aguilar",
    last: "Aguilar",
    role: "Secretary of Marketing",
    group: "Secretaries",
  },
  {
    name: "Vince Carlo Radima",
    last: "Radima",
    role: "Secretary of Communications",
    group: "Secretaries",
  },
  {
    name: "Miguel Carlos Suela",
    last: "Suela",
    role: "Secretary of Creatives",
    group: "Secretaries",
  },
  {
    name: "Effeny Capalaran",
    last: "Capalaran",
    role: "Secretary of Multimedia",
    group: "Secretaries",
  },
  {
    name: "Siegfried Gaerlan",
    last: "Gaerlan",
    role: "Secretary of Technology",
    group: "Secretaries",
  },
  {
    name: "Jake Mayores",
    last: "Mayores",
    role: "Assistant Secretary of Technology",
    group: "Secretaries",
  },
  {
    name: "Precious Villagracia",
    last: "Villagracia",
    role: "Secretary of Logistics",
    group: "Secretaries",
  },

  {
    name: "Vince Carlo Radima",
    last: "Radima",
    role: "Secretary of Communications",
    group: "Communications",
  },
  {
    name: "Lj Ann Andrada",
    last: "Andrada",
    role: "Communication Officer",
    group: "Communications",
  },

  {
    name: "Miguel Carlos Suela",
    last: "Suela",
    role: "Secretary of Creatives",
    group: "Creatives",
  },
  {
    name: "Danielle Alanne Tomale",
    last: "Tomale",
    role: "Creatives Associate",
    group: "Creatives",
  },

  {
    name: "Jannah Mari Baloloy",
    last: "Baloloy",
    role: "Secretary of Finance",
    group: "Finance",
  },
  {
    name: "Daniel Irvin Espiritu",
    last: "Espiritu",
    role: "Finance Associate",
    group: "Finance",
  },
  {
    name: "Angela Delfin",
    last: "Delfin",
    role: "Finance Associate",
    group: "Finance",
  },

  {
    name: "Precious Villagracia",
    last: "Villagracia",
    role: "Secretary of Logistics",
    group: "Logistics",
  },
  {
    name: "Michael Grace",
    last: "Grace",
    role: "Logistics Associate",
    group: "Logistics",
  },
  {
    name: "Zeji Arnoco",
    last: "Arnoco",
    role: "Logistics Associate",
    group: "Logistics",
  },

  {
    name: "Cayril Aguilar",
    last: "Aguilar",
    role: "Secretary of Marketing",
    group: "Marketing",
  },

  {
    name: "Effeny Capalaran",
    last: "Capalaran",
    role: "Media and Design Associate",
    group: "Multimedia",
  },
  {
    name: "Nathan Ar-Ed Briones",
    last: "Briones",
    role: "Multimedia Associate",
    group: "Multimedia",
  },
  {
    name: "Clarence Jeane Bolibol",
    last: "Bolibol",
    role: "Secretary of Records",
    group: "Records",
  },
  {
    name: "Lourd Zayen Vallejo",
    last: "Vallejo",
    role: "Records Associate",
    group: "Records",
  },
  {
    name: "Jared Emery Dela Rosa",
    last: "Dela Rosa",
    role: "Records Associate",
    group: "Records",
  },
  {
    name: "Maria Julia Landoy",
    last: "Landoy",
    role: "Records Associate",
    group: "Records",
  },
  {
    name: "Leane Jean Muli",
    last: "Muli",
    role: "Records Associate",
    group: "Records",
  },
  {
    name: "Siegfried Gaerlan",
    last: "Gaerlan",
    role: "Tech Associate",
    group: "Technology",
  },
  {
    name: "Jake Mayores",
    last: "Mayores",
    role: "Tech Associate",
    group: "Technology",
  },
  {
    name: "E-Jhay Esplana",
    last: "Esplana",
    role: "Development Associate (I created this website!)",
    group: "Technology",
  },
  {
    name: "Jeric Rectin",
    last: "Rectin",
    role: "Development Associate",
    group: "Technology",
  },
  {
    name: "Ren Charlly Libramonte",
    last: "Libramonte",
    role: "Development Associate",
    group: "Technology",
  },
  {
    name: "Marc Nelson Belasa",
    last: "Belasa",
    role: "Development Associate",
    group: "Technology",
  },
  {
    name: "John Ashley Dulay",
    last: "Dulay",
    role: "UI/UX Associate",
    group: "Technology",
  },
  {
    name: "Jervies Mhon Pasion",
    last: "Pasion",
    role: "UI/UX Associate",
    group: "Technology",
  },

  {
    name: "Anjo Saraga",
    last: "Saraga",
    role: "Former Finance Associate",
    group: "Former Officers",
  },
  {
    name: "Athea Jayne Ahorro",
    last: "Ahorro",
    role: "Former VP Externals",
    group: "Former Officers",
  },
  {
    name: "Cyril Pahimnayan",
    last: "Pahimnayan",
    role: "Former Creatives Associate",
    group: "Former Officers",
  },
  {
    name: "Felicity Chiqui Pariña",
    last: "Pariña",
    role: "Former Secretary of Logistics",
    group: "Former Officers",
  },
  {
    name: "Great Britain Rendon",
    last: "Rendon",
    role: "Former Tech Assistant Secretary",
    group: "Former Officers",
  },
  {
    name: "Harley Stephen Soldao",
    last: "Soldao",
    role: "Former VP Internals",
    group: "Former Officers",
  },
  {
    name: "John Rohan Acebo",
    last: "Acebo",
    role: "Former Development Associate",
    group: "Former Officers",
  },
  {
    name: "Kyle Erica Santos",
    last: "Santos",
    role: "Former Graphics Lead Designer",
    group: "Former Officers",
  },
  {
    name: "Lord Richmach Abulencia Go",
    last: "Go",
    role: "Former Logistic Associate",
    group: "Former Officers",
  },
  {
    name: "Marc Plarisan",
    last: "Plarisan",
    role: "Former Development Associate",
    group: "Former Officers",
  },
  {
    name: "Marielle Psyche Valle",
    last: "Valle",
    role: "Former Secretary of Marketing",
    group: "Former Officers",
  },
  {
    name: "Mark Joseph Morcozo",
    last: "Morcozo",
    role: "Former Secretary of Media and Design",
    group: "Former Officers",
  },
  {
    name: "Maui Rayos",
    last: "Rayos",
    role: "Former Secretary of Technology",
    group: "Former Officers",
  },
  {
    name: "Nicolette Wilma Fabros",
    last: "Fabros",
    role: "Former Finance Associate",
    group: "Former Officers",
  },
  {
    name: "Paolo Mickell Buenaventura",
    last: "Buenaventura",
    role: "Former Logistic Associate",
    group: "Former Officers",
  },
  {
    name: "Rhaya Shane Revellame",
    last: "Revellame",
    role: "Former Creatives Associate",
    group: "Former Officers",
  },
  {
    name: "Riener Jay Revellame",
    last: "Revellame",
    role: "Former Logistic Associate",
    group: "Former Officers",
  },
  {
    name: "Yuhan Santy Salandanan",
    last: "Salandanan",
    role: "Former Logistic Associate",
    group: "Former Officers",
  },
];
